### ISSUE TITLE
WireError - example program 

### ISSUE THREAD

**Issue by NicolasHaeffner** [plietar/librespot#172]
I was able to compile the code and am _sometimes_ able to get the example program running, but often this Error is thrown: 
```
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 12")', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
note: Run with `RUST_BACKTRACE=1` for a backtrace.`
```
is there anything I can do about this?

**Comment by plietar** [comment]
Thanks for opening the issue.
This happens every now and then when Spotify add new features.

Could you please set the `RUST_BACKTRACE` environment variable to 1 and try again

**Comment by NicolasHaeffner** [comment]
Hi, thanks for the response :)
 here is the output with `RUST_BACKTRACE=1` : 

```
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 12")', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x56347a94286c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x56347a9475ae - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x56347a9471b4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x56347a947a4b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x56347a9478e4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x56347a947809 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x56347a947797 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x56347a972e5d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x56347a647b29 - core::result::unwrap_failed::h8df64c572d1422eb
  10:     0x56347a679ab3 - <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll::h14ae4c971b29156d
  11:     0x56347a6afd75 - <librespot::spirc::SpircTask as futures::future::Future>::poll::hdea4718980fe6cdd
  12:     0x56347a61ea22 - librespot::main::h07f52f461455f4d5
  13:     0x56347a94ea3a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x56347a9481b6 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  15:     0x7f50e092682f - __libc_start_main
  16:     0x56347a60d928 - _start
  17:                0x0 - <unknown>
```

I have noticed, that it crashes as soon as I try to connect it with for instance the Spotify Application for mac (as soon as I start the application)

**Comment by plietar** [comment]
This should be fixed now, please let me know if you're still having issues

**Comment by NicolasHaeffner** [comment]
Seems to work, thank you!
Keep up the good work :)
