### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(Utf8Error)', 

### ISSUE THREAD

**Issue by Rdlgrmpf** [plietar/librespot#236]
Hi,
running on RPi 3, started with the command:
`RUST_BACKTRACE=1 librespot -b 320 --name "Die Beere" --backend alsa --verbose`

I get the following error when trying to connect a device. The error occurs even before starting a song.
librespot crashes after that.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(Utf8Error)', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll
  11: <librespot::spirc::SpircTask as futures::future::Future>::poll
  12: <futures::task_impl::Spawn<T>>::enter::{{closure}}
  13: librespot::main
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  16: __libc_start_main`

**Comment by Rdlgrmpf** [comment]
uname -a

Linux robinsbeere 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by Rdlgrmpf** [comment]
same error as https://github.com/plietar/librespot/issues/170.

Sorry for bothering. But at least you now know that emojis are still an issue :)
