### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error

### ISSUE THREAD

**Issue by krooarbo** [plietar/librespot#238]
Hi,

First of all sorry for my english.
Yesterday libresport is working, but today not working. There isnt any changes on the system.

RUST_BACKTRACE=1 librespot --backend alsa -n raspotify --username  $MYUSER --password $MYPASS
INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-07. Build ID: N5RcEuis
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 19, message: "No such device" } }', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main

Please help!
Thanks in advance!

Br,

**Comment by krooarbo** [comment]
0-12 is \<unknown\>

**Comment by chimpy** [comment]
I have the same error.

**Comment by flori4n** [comment]
Hello,

Same issue, I can't have access with a family account. I'm not sure if that something in your side or on spotify side.
I have a friend who's also premium and he's able to join and play my raspotify but I can't. (i can see it on my android but when I try the device it "pauses"
Any idea?

INFO:librespot_core::session: Country: "CH" thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:860:4 note: Run withRUST_BACKTRACE=1for a backtrace. INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-51qb.ap.spotify.com:4070" INFO:librespot_core::session: Authenticated as "xxxxxxxxx" ! INFO:librespot::audio_backend::alsa: Using alsa sink INFO:librespot_core::session: Country: "CH" thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:860:4 note: Run withRUST_BACKTRACE=1for a backtrace. INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg

Thanks you

**Comment by sashahilton00** [comment]
This has been fixed. The solution is to use the new repo https://github.com/librespot-org/librespot, rebuild librespot, and you won't see this error anymore.
