### ISSUE TITLE
librespot built with lewton support crashes after first song

### ISSUE THREAD

**Issue by awiouy** [plietar/librespot#248]
librespot built with lewton support crashes after first song with the following messages:
```
thread '<unnamed>' panicked at ' error: OggError(NoCapturePatternFound)', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:860:4
```

Running with RUST_BACKTRACE=1 does not provide further information:
```
thread '<unnamed>' panicked at 'Vorbis error: OggError(NoCapturePatternFound)', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: <unknown>
```
The above messages were issued while using ALSA backend.

librespot was built with Rust 1.20.0:
`$CARGO_BUILD --no-default-features --features "alsa-backend pulseaudio-backend with-lewton"`

**Comment by sstickel** [comment]
Anybody found a solution to this? Made librespot pretty unusable for me, as after a few tracks librespots always panicks and dies.
