### ISSUE TITLE
librespot crashes - main thread panic

### ISSUE THREAD

**Issue by pwitka2** [plietar/librespot#273]
librespot crashes with such error message:

**INFO:librespot::player: Track "Sweet Pea" loaded
thread 'main' panicked at 'Box<Any>', core/src/session.rs:83:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.**

It happened after long idle (paused) time.

I have raspbian wheezy
raspotify 0.9.1~librespot.20171005T125424Z.8971d3a

**Comment by kingosticks** [comment]
I would suggest you run RUST_BACKTRACE=1 and provide the backtrace.

**Comment by pwitka2** [comment]
Here is a backtrace, but app crashes in different place:
INFO:librespot::player: Track "Magic Wind" loaded
thread 'main' panicked at 'connection closed', /checkout/src/libcore/option.rs:819:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main

**Comment by kingosticks** [comment]
Raspotify seem to have decided to strip the binary. That's not helpful.
