### ISSUE TITLE
Compilation fails on rust nightlies after 18.01.2016

### ISSUE THREAD

**Issue by psych0d0g** [plietar/librespot#42]
```
thread '<main>' panicked at 'destination and source slices have different lengths', ../src/libcore/slice.rs:479
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: AsyncError::Aborted', ../src/libcore/result.rs:688
```

probably this change:
https://github.com/rust-lang/rust/commit/6a7bc47a8f1bf4441ca55e42aa50db6dda28181f

**Comment by plietar** [comment]
This was caused by Spotify sending an AudioFile object with no id.
