### ISSUE TITLE
Crash when playing a particular song

### ISSUE THREAD

**Issue by paradis** [plietar/librespot#74]
Hello,

A crash occurs when I try to play [this song](https://play.spotify.com/user/korgald/playlist/7iWv2BVixXs0elIzLoVKWq).

It's compiled on a Raspberry Pi 2 from master. Here is the backtrace (the program was still hanging, don't know if it is relevant).

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
stack backtrace:
   1: 0x54d0e22f - sys::backtrace::tracing::imp::write::h915bdba0cf2b7eb2yju
   2: 0x54d10d7b - panicking::default_handler::_<closure>::closure.42462
   3: 0x54d107c3 - panicking::default_handler::h5649abd342504206ryy
   4: 0x54cfb61f - sys_common::unwind::begin_unwind_inner::h411a20ea9dff208d5bt
   5: 0x54cfc057 - sys_common::unwind::begin_unwind_fmt::h23d12c3e5d53eabcbbt
   6: 0x54d0d7d3 - rust_begin_unwind
   7: 0x54d18e6f - panicking::panic_fmt::h6a4d01d6dfe84597zYL
   8: 0x54c030c3 - player::Player::command::hb0a29a5db46ae0996Gc
   9: 0x54c4aa2f - spirc::SpircManager::run::h6a87ab8ff491ece0Ykd
  10: 0x54bc1d6f - sys_common::unwind::try::try_fn::h15239427894743543715
  11: 0x54d0d773 - __rust_try
  12: 0x54d0d773 - __rust_try
```

When using https://github.com/crsmoro/scplayer and libspotify_embedded_shared.so, another crash occur but locally it plays fine. So maybe it's a problem in spotify connect rather than in librespot; but it would be nice if librespot could recover from this error.

Since I'm not used to report rust bugs, please let me know if you need additional info or any help!

Thanks!

**Comment by marcust** [comment]
I have a crashing song as well, with the following backtrace:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 11")', ../src/libcore/result.rs:746
stack backtrace:
   1: 0x550237fb - sys::backtrace::tracing::imp::write::hc1e18f730a9d389aYGv
   2: 0x550264bf - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44908
   3: 0x5502603f - panicking::default_handler::h6142a5aea96b0101EpA
   4: 0x55012bdf - sys_common::unwind::begin_unwind_inner::hca67b1c5fc288486hvu
   5: 0x55013113 - sys_common::unwind::begin_unwind_fmt::h5dbd49e31ef67471nuu
   6: 0x55022d0b - rust_begin_unwind
   7: 0x5503142b - panicking::panic_fmt::h5cb8261bde3e5c7aycM
   8: 0x54cf0d17 - result::unwrap_failed::h11639913525070013829
                at ../src/libcore/macros.rs:29
   9: 0x54d1c67b - result::Result<T, E>::unwrap::h15729366091306238074
                at ../src/libcore/result.rs:687
  10: 0x54d1bfd7 - metadata::MetadataManager::get::_$u7b$$u7b$closure$u7d$$u7d$::closure.30150
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2116
  11: 0x54d1b20f - eventual::Async::and_then::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.30116
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/lib.rs:203
  12: 0x54d1a56f - eventual::Async::receive::_$u7b$$u7b$closure$u7d$$u7d$::closure.30111
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/lib.rs:123
  13: 0x54d1976f - eventual::future::Future<T, E>.Async::ready::_$u7b$$u7b$closure$u7d$$u7d$::closure.30104
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/future.rs:209
  14: 0x54d198d3 - F.BoxedReceive<T>::receive_boxed::h10355481238812217259
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/lib.rs:451
  15: 0x54c403e7 - core::CoreInner<T, E>::notify_consumer_loop::h6958505536731022698
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/core.rs:370
  16: 0x54c3fd2b - core::CoreInner<T, E>::notify_consumer::h9268056314664434700
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/core.rs:339
  17: 0x54c3f4ab - core::CoreInner<T, E>::complete::h1376479605005745706
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/core.rs:636
  18: 0x54c3ea1f - core::Core<T, E>::complete::h12208942482453312364
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/core.rs:102
  19: 0x54cf14e3 - future::Complete<T, E>::complete::h18018738566500177901
                at /home/marcus/.cargo/registry/src/github.com-48ad6e4054423464/eventual-0.1.6/src/future.rs:288
  20: 0x54cf0043 - mercury::MercuryManager::complete_request::h17f8654ed98c2e77iMc
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:1866
  21: 0x54cf59cb - mercury::MercuryManager.PacketHandler::handle::hec5a2101603ec8a9tPc
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:1939
  22: 0x54d4a82f - session::Session::poll::h1576aed4b4cbae98tPd
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2680
  23: 0x54bda2c7 - main::h1bf9f058f8fd1944Lba
                at src/main.rs:60
  24: 0x55025c27 - sys_common::unwind::try::try_fn::h5242781930021139518
```

The song being https://open.spotify.com/track/2a6dVVMaky4yKuxk9hmWwn

I unfortunately don't understand which enum is meant and how to solve that.

**Comment by plietar** [comment]
Unfortunately rust-protobuf does not handle new enum values gracefully. Relevant issue: https://github.com/stepancheg/rust-protobuf/issues/108

Does adding a dummy entry with value 0xb to the AudioFile.Format of metadata.proto file help ?
I'll look into it in more detail later.

**Comment by marcust** [comment]
Yes,  that solves the crash, newer songs seem to have more values there, at least it got worse in the last 24 hours

**Comment by marcust** [comment]
They seem to have changed a lot of other stuff as well, now it is directly crashing on startup:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 11")', ../src/libcore/result.rs:746
stack backtrace:
   1: 0x54fae8f3 - sys::backtrace::tracing::imp::write::hc1e18f730a9d389aYGv
   2: 0x54fb15b7 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44908
   3: 0x54fb1137 - panicking::default_handler::h6142a5aea96b0101EpA
   4: 0x54f9dcd7 - sys_common::unwind::begin_unwind_inner::hca67b1c5fc288486hvu
   5: 0x54f9e20b - sys_common::unwind::begin_unwind_fmt::h5dbd49e31ef67471nuu
   6: 0x54fade03 - rust_begin_unwind
   7: 0x54fbc523 - panicking::panic_fmt::h5cb8261bde3e5c7aycM
   8: 0x54c7bd17 - result::unwrap_failed::h12582494576691141292
                at ../src/libcore/macros.rs:29
   9: 0x54cf304b - result::Result<T, E>::unwrap::h14001304564491511816
                at ../src/libcore/result.rs:687
  10: 0x54ced10b - spirc::SpircManager::run::he7b1660863271901CZd
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2857
  11: 0x54b94967 - main::_$u7b$$u7b$closure$u7d$$u7d$::closure.13568
                at src/main.rs:57
  12: 0x54b94597 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.13557
                at ../src/libstd/thread/mod.rs:278
  13: 0x54b9455f - sys_common::unwind::try::try_fn::h5047992088056050143
                at ../src/libstd/sys/common/unwind/mod.rs:127
  14: 0x54fadd9b - __rust_try
  15: 0x54fadd9b - __rust_try
  16: 0x54fadd9b - __rust_try
  17: 0x54fadd9b - __rust_try
  18: 0x54fadd9b - __rust_try
  19: 0x54fadd9b - __rust_try
  20: 0x54fadd9b - __rust_try
  21: 0x54fadd9b - __rust_try
  22: 0x54fadd9b - __rust_try
  23: 0x54fadd9b - __rust_try
  24: 0x54fadd9b - __rust_try
  25: 0x54fadd9b - __rust_try
  26: 0x54fadd9b - __rust_try
  27: 0x54fadd9b - __rust_try
  28: 0x54fadd9b - __rust_try
  29: 0x54fadd9b - __rust_try
  30: 0x54fadd9b - __rust_try
  31: 0x54fadd9b - __rust_try
  32: 0x54fadd9b - __rust_try
  33: 0x54fadd9b - __rust_try
  34: 0x54fadd9b - __rust_try
  35: 0x54fadd9b - __rust_try
  36: 0x54fadd9b - __rust_try
  37: 0x54fadd9b - __rust_try
  38: 0x54fadd9b - __rust_try
  39: 0x54fadd9b - __rust_try
  40: 0x54fadd9b - __rust_try
  41: 0x54fadd9b - __rust_try
  42: 0x54fadd9b - __rust_try
  43: 0x54fadd9b - __rust_try
  44: 0x54fadd9b - __rust_try
  45: 0x54fadd9b - __rust_try
  46: 0x54fadd9b - __rust_try
  47: 0x54fadd9b - __rust_try
  48: 0x54fadd9b - __rust_try
  49: 0x54fadd9b - __rust_try
  50: 0x54fadd9b - __rust_try
  51: 0x54fadd9b - __rust_try
  52: 0x54fadd9b - __rust_try
  53: 0x54fadd9b - __rust_try
  54: 0x54fadd9b - __rust_try
  55: 0x54fadd9b - __rust_try
  56: 0x54fadd9b - __rust_try
  57: 0x54fadd9b - __rust_try
  58: 0x54fadd9b - __rust_try
  59: 0x54fadd9b - __rust_try
  60: 0x54fadd9b - __rust_try
  61: 0x54fadd9b - __rust_try
  62: 0x54fadd9b - __rust_try
  63: 0x54fadd9b - __rust_try
  64: 0x54fadd9b - __rust_try
  65: 0x54fadd9b - __rust_try
  66: 0x54fadd9b - __rust_try
  67: 0x54fadd9b - __rust_try
  68: 0x54fadd9b - __rust_try
  69: 0x54fadd9b - __rust_try
  70: 0x54fadd9b - __rust_try
  71: 0x54fadd9b - __rust_try
  72: 0x54fadd9b - __rust_try
  73: 0x54fadd9b - __rust_try
  74: 0x54fadd9b - __rust_try
  75: 0x54fadd9b - __rust_try
  76: 0x54fadd9b - __rust_try
  77: 0x54fadd9b - __rust_try
  78: 0x54fadd9b - __rust_try
  79: 0x54fadd9b - __rust_try
  80: 0x54fadd9b - __rust_try
  81: 0x54fadd9b - __rust_try
  82: 0x54fadd9b - __rust_try
  83: 0x54fadd9b - __rust_try
  84: 0x54fadd9b - __rust_try
  85: 0x54fadd9b - __rust_try
  86: 0x54fadd9b - __rust_try
  87: 0x54fadd9b - __rust_try
  88: 0x54fadd9b - __rust_try
  89: 0x54fadd9b - __rust_try
  90: 0x54fadd9b - __rust_try
  91: 0x54fadd9b - __rust_try
  92: 0x54fadd9b - __rust_try
  93: 0x54fadd9b - __rust_try
  94: 0x54fadd9b - __rust_try
  95: 0x54fadd9b - __rust_try
  96: 0x54fadd9b - __rust_try
  97: 0x54fadd9b - __rust_try
  98: 0x54fadd9b - __rust_try
  99: 0x54fadd9b - __rust_try
  100: 0x54fadd9b - __rust_try
 ... <frames omitted>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
stack backtrace:
   1: 0x54fae8f3 - sys::backtrace::tracing::imp::write::hc1e18f730a9d389aYGv
   2: 0x54fb15b7 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44908
   3: 0x54fb1137 - panicking::default_handler::h6142a5aea96b0101EpA
   4: 0x54f9dcd7 - sys_common::unwind::begin_unwind_inner::hca67b1c5fc288486hvu
   5: 0x54f9e20b - sys_common::unwind::begin_unwind_fmt::h5dbd49e31ef67471nuu
   6: 0x54fade03 - rust_begin_unwind
   7: 0x54fbc523 - panicking::panic_fmt::h5cb8261bde3e5c7aycM
   8: 0x54c58a7f - result::unwrap_failed::h12673796802908104007
                at ../src/libcore/macros.rs:29
   9: 0x54c977c3 - result::Result<T, E>::unwrap::h16273725647864597816
                at ../src/libcore/result.rs:687
  10: 0x54c93937 - player::PlayerInternal::run::h5f2333972291c91eWjd
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2257
  11: 0x54d1da9b - player::Player::new::_$u7b$$u7b$closure$u7d$$u7d$::closure.33752
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2208
  12: 0x54d1d5d7 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::closure.33741
                at ../src/libstd/thread/mod.rs:278
  13: 0x54d1d567 - sys_common::unwind::try::try_fn::h2175881239980325150
                at ../src/libstd/sys/common/unwind/mod.rs:127
  14: 0x54fadd9b - __rust_try
  15: 0x54fadd9b - __rust_try
  16: 0x54fadd9b - __rust_try
  17: 0x54fadd9b - __rust_try
  18: 0x54fadd9b - __rust_try
  19: 0x54fadd9b - __rust_try
  20: 0x54fadd9b - __rust_try
  21: 0x54fadd9b - __rust_try
  22: 0x54fadd9b - __rust_try
  23: 0x54fadd9b - __rust_try
  24: 0x54fadd9b - __rust_try
  25: 0x54fadd9b - __rust_try
  26: 0x54fadd9b - __rust_try
  27: 0x54fadd9b - __rust_try
  28: 0x54fadd9b - __rust_try
  29: 0x54fadd9b - __rust_try
  30: 0x54fadd9b - __rust_try
  31: 0x54fadd9b - __rust_try
  32: 0x54fadd9b - __rust_try
  33: 0x54fadd9b - __rust_try
  34: 0x54fadd9b - __rust_try
  35: 0x54fadd9b - __rust_try
  36: 0x54fadd9b - __rust_try
  37: 0x54fadd9b - __rust_try
  38: 0x54fadd9b - __rust_try
  39: 0x54fadd9b - __rust_try
  40: 0x54fadd9b - __rust_try
  41: 0x54fadd9b - __rust_try
  42: 0x54fadd9b - __rust_try
  43: 0x54fadd9b - __rust_try
  44: 0x54fadd9b - __rust_try
  45: 0x54fadd9b - __rust_try
  46: 0x54fadd9b - __rust_try
  47: 0x54fadd9b - __rust_try
  48: 0x54fadd9b - __rust_try
  49: 0x54fadd9b - __rust_try
  50: 0x54fadd9b - __rust_try
  51: 0x54fadd9b - __rust_try
  52: 0x54fadd9b - __rust_try
  53: 0x54fadd9b - __rust_try
  54: 0x54fadd9b - __rust_try
  55: 0x54fadd9b - __rust_try
  56: 0x54fadd9b - __rust_try
  57: 0x54fadd9b - __rust_try
  58: 0x54fadd9b - __rust_try
  59: 0x54fadd9b - __rust_try
  60: 0x54fadd9b - __rust_try
  61: 0x54fadd9b - __rust_try
  62: 0x54fadd9b - __rust_try
  63: 0x54fadd9b - __rust_try
  64: 0x54fadd9b - __rust_try
  65: 0x54fadd9b - __rust_try
  66: 0x54fadd9b - __rust_try
  67: 0x54fadd9b - __rust_try
  68: 0x54fadd9b - __rust_try
  69: 0x54fadd9b - __rust_try
  70: 0x54fadd9b - __rust_try
  71: 0x54fadd9b - __rust_try
  72: 0x54fadd9b - __rust_try
  73: 0x54fadd9b - __rust_try
  74: 0x54fadd9b - __rust_try
  75: 0x54fadd9b - __rust_try
  76: 0x54fadd9b - __rust_try
  77: 0x54fadd9b - __rust_try
  78: 0x54fadd9b - __rust_try
  79: 0x54fadd9b - __rust_try
  80: 0x54fadd9b - __rust_try
  81: 0x54fadd9b - __rust_try
  82: 0x54fadd9b - __rust_try
  83: 0x54fadd9b - __rust_try
  84: 0x54fadd9b - __rust_try
  85: 0x54fadd9b - __rust_try
  86: 0x54fadd9b - __rust_try
  87: 0x54fadd9b - __rust_try
  88: 0x54fadd9b - __rust_try
  89: 0x54fadd9b - __rust_try
  90: 0x54fadd9b - __rust_try
  91: 0x54fadd9b - __rust_try
  92: 0x54fadd9b - __rust_try
  93: 0x54fadd9b - __rust_try
  94: 0x54fadd9b - __rust_try
  95: 0x54fadd9b - __rust_try
  96: 0x54fadd9b - __rust_try
  97: 0x54fadd9b - __rust_try
  98: 0x54fadd9b - __rust_try
  99: 0x54fadd9b - __rust_try
  100: 0x54fadd9b - __rust_try
 ... <frames omitted>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
stack backtrace:
   1: 0x54fae8f3 - sys::backtrace::tracing::imp::write::hc1e18f730a9d389aYGv
   2: 0x54fb15b7 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44908
   3: 0x54fb1137 - panicking::default_handler::h6142a5aea96b0101EpA
   4: 0x54f9dcd7 - sys_common::unwind::begin_unwind_inner::hca67b1c5fc288486hvu
   5: 0x54f9e20b - sys_common::unwind::begin_unwind_fmt::h5dbd49e31ef67471nuu
   6: 0x54fade03 - rust_begin_unwind
   7: 0x54fbc523 - panicking::panic_fmt::h5cb8261bde3e5c7aycM
   8: 0x54c7d7c7 - result::unwrap_failed::h4523123209359368742
                at ../src/libcore/macros.rs:29
   9: 0x54c7d5f3 - result::Result<T, E>::unwrap::h9250863514847239027
                at ../src/libcore/result.rs:687
  10: 0x54c7c6df - mercury::MercuryManager::complete_request::_$u7b$$u7b$closure$u7d$$u7d$::closure.29246
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:1871
  11: 0x54c7c5f3 - option::Option<T>::map::h13101957425955516617
                at ../src/libcore/option.rs:390
  12: 0x54c7b227 - mercury::MercuryManager::complete_request::hf87a87b1cd72034biMc
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:1870
  13: 0x54c809cb - mercury::MercuryManager.PacketHandler::handle::hddfbc1dfa71d3ef4tPc
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:1939
  14: 0x54cd58b7 - session::Session::poll::ha9f9ac4fb1122efftPd
                at target/debug/build/librespot-6b2cdadcae310c16/out/lib.rs:2680
  15: 0x54b652c7 - main::h1bf9f058f8fd1944Lba
                at src/main.rs:60
  16: 0x54fb0d1f - sys_common::unwind::try::try_fn::h5242781930021139518
  17: 0x54fadd9b - __rust_try
  18: 0x54fadd9b - __rust_try
  19: 0x54fadd9b - __rust_try
  20: 0x54fadd9b - __rust_try
  21: 0x54fadd9b - __rust_try
  22: 0x54fadd9b - __rust_try
  23: 0x54fadd9b - __rust_try
  24: 0x54fadd9b - __rust_try
  25: 0x54fadd9b - __rust_try
  26: 0x54fadd9b - __rust_try
  27: 0x54fadd9b - __rust_try
  28: 0x54fadd9b - __rust_try
  29: 0x54fadd9b - __rust_try
  30: 0x54fadd9b - __rust_try
  31: 0x54fadd9b - __rust_try
  32: 0x54fadd9b - __rust_try
  33: 0x54fadd9b - __rust_try
  34: 0x54fadd9b - __rust_try
  35: 0x54fadd9b - __rust_try
  36: 0x54fadd9b - __rust_try
  37: 0x54fadd9b - __rust_try
  38: 0x54fadd9b - __rust_try
  39: 0x54fadd9b - __rust_try
  40: 0x54fadd9b - __rust_try
  41: 0x54fadd9b - __rust_try
  42: 0x54fadd9b - __rust_try
  43: 0x54fadd9b - __rust_try
  44: 0x54fadd9b - __rust_try
  45: 0x54fadd9b - __rust_try
  46: 0x54fadd9b - __rust_try
  47: 0x54fadd9b - __rust_try
  48: 0x54fadd9b - __rust_try
  49: 0x54fadd9b - __rust_try
  50: 0x54fadd9b - __rust_try
  51: 0x54fadd9b - __rust_try
  52: 0x54fadd9b - __rust_try
  53: 0x54fadd9b - __rust_try
  54: 0x54fadd9b - __rust_try
  55: 0x54fadd9b - __rust_try
  56: 0x54fadd9b - __rust_try
  57: 0x54fadd9b - __rust_try
  58: 0x54fadd9b - __rust_try
  59: 0x54fadd9b - __rust_try
  60: 0x54fadd9b - __rust_try
  61: 0x54fadd9b - __rust_try
  62: 0x54fadd9b - __rust_try
  63: 0x54fadd9b - __rust_try
  64: 0x54fadd9b - __rust_try
  65: 0x54fadd9b - __rust_try
  66: 0x54fadd9b - __rust_try
  67: 0x54fadd9b - __rust_try
  68: 0x54fadd9b - __rust_try
  69: 0x54fadd9b - __rust_try
  70: 0x54fadd9b - __rust_try
  71: 0x54fadd9b - __rust_try
  72: 0x54fadd9b - __rust_try
  73: 0x54fadd9b - __rust_try
  74: 0x54fadd9b - __rust_try
  75: 0x54fadd9b - __rust_try
  76: 0x54fadd9b - __rust_try
  77: 0x54fadd9b - __rust_try
  78: 0x54fadd9b - __rust_try
  79: 0x54fadd9b - __rust_try
  80: 0x54fadd9b - __rust_try
  81: 0x54fadd9b - __rust_try
  82: 0x54fadd9b - __rust_try
  83: 0x54fadd9b - __rust_try
  84: 0x54fadd9b - __rust_try
  85: 0x54fadd9b - __rust_try
  86: 0x54fadd9b - __rust_try
  87: 0x54fadd9b - __rust_try
  88: 0x54fadd9b - __rust_try
  89: 0x54fadd9b - __rust_try
  90: 0x54fadd9b - __rust_try
  91: 0x54fadd9b - __rust_try
  92: 0x54fadd9b - __rust_try
  93: 0x54fadd9b - __rust_try
  94: 0x54fadd9b - __rust_try
  95: 0x54fadd9b - __rust_try
  96: 0x54fadd9b - __rust_try
  97: 0x54fadd9b - __rust_try
  98: 0x54fadd9b - __rust_try
  99: 0x54fadd9b - __rust_try
  100: 0x54fadd9b - __rust_try
 ... <frames omitted>
```

**Comment by b-per** [comment]
Same here.

If I close all my Spotify clients, I have no error until I launch one of them (no matter if it is the OSX desktop client or the iOS one). But as soon as the client opens, librespot crashes with the same errors are above.

If I start librespot when some clients are opened it crashes directly.

**Comment by plietar** [comment]
@camfrout this should be fixed by @marcust's PRs.
@paradis does that fix it for you ? You've only included the end of the log. librespot uses a few threads and when one of them crashes, the others fall with it. SendError/RecvError are usually the other threads crashing, the first panic in the log is the interesting one.

**Comment by b-per** [comment]
Yes, it is working with @marcust fix. Thanks a lot. 

How is it possible to identify where the issue comes from when librespot crashes? I don't see  anything about a protobuf issue in the debug log. I would be glad to help fixing librespot when I face errors but I have no idea where to look when the program crashes.

**Comment by paradis** [comment]
Thank you very much for looking into this.

The song has been removed from Spotify, so my example above is not valid anymore.

I managed to reproduced the crash while trying to play a [playlist with removed songs](https://open.spotify.com/user/cmabraham/playlist/6STruCKEA0Hee66fV7R8nS). However, since this playlist is also invalid with the desktop client, I think you can close this issue if the problem is not trivial.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1: 0x5506839b - sys::backtrace::tracing::imp::write::h915bdba0cf2b7eb2yju
   2: 0x5506aee7 - panicking::default_handler::_<closure>::closure.42462
   3: 0x5506a92f - panicking::default_handler::h5649abd342504206ryy
   4: 0x55055dcf - sys_common::unwind::begin_unwind_inner::h411a20ea9dff208d5bt
   5: 0x55056807 - sys_common::unwind::begin_unwind_fmt::h23d12c3e5d53eabcbbt
   6: 0x5506793f - rust_begin_unwind
   7: 0x55072fdb - panicking::panic_fmt::h6a4d01d6dfe84597zYL
   8: 0x5507335f - panicking::panic::haab165e34c7b32c76WL
   9: 0x54d4f5c7 - option::Option<T>::unwrap::h9247533625232163396
                at ../src/libcore/macros.rs:21
  10: 0x54d2f7d7 - player::PlayerInternal::run::h8539af5c37b429e4eKc
                at target/debug/build/librespot-4f8a28a86014895a/out/lib.rs:2163
  11: 0x54dce207 - player::Player::new::_<closure>::closure.29940
                at target/debug/build/librespot-4f8a28a86014895a/out/lib.rs:2091
  12: 0x54dcdb9b - std::thread::Builder::spawn::_<closure>::_<closure>::closure.29929
                at ../src/libstd/thread/mod.rs:277
  13: 0x54dcdb03 - sys_common::unwind::try::try_fn::h8664025515847058403
                at ../src/libstd/sys/common/unwind/mod.rs:153
  14: 0x550678df - __rust_try
  15: 0x550678df - __rust_try
  16: 0x550678df - __rust_try
  17: 0x550678df - __rust_try
  18: 0x550678df - __rust_try
  19: 0x550678df - __rust_try
  20: 0x550678df - __rust_try
  21: 0x550678df - __rust_try
  22: 0x550678df - __rust_try
  23: 0x550678df - __rust_try
```
